//! AES-CBC helpers, MD5, and the EcoFlow session-key derivation.

use aes::cipher::{block_padding::Pkcs7, BlockDecryptMut, BlockEncryptMut, KeyIvInit};
use md5::{Digest, Md5};

type Enc = cbc::Encryptor<aes::Aes128>;
type Dec = cbc::Decryptor<aes::Aes128>;

/// The universal login key (deterministic, not per-user) used in session-key
/// derivation. Generated by `ef-ble-reverse`'s `login_key_gen.py`.
pub const LOGIN_KEY: &[u8] = include_bytes!("login_key.bin");

pub fn md5(data: &[u8]) -> [u8; 16] {
    let mut h = Md5::new();
    h.update(data);
    h.finalize().into()
}

/// AES-128-CBC encrypt with PKCS7 padding.
pub fn aes_cbc_encrypt(key: &[u8; 16], iv: &[u8; 16], data: &[u8]) -> Vec<u8> {
    Enc::new(key.into(), iv.into()).encrypt_padded_vec_mut::<Pkcs7>(data)
}

/// AES-128-CBC decrypt with PKCS7 unpadding.
pub fn aes_cbc_decrypt(key: &[u8; 16], iv: &[u8; 16], data: &[u8]) -> Option<Vec<u8>> {
    Dec::new(key.into(), iv.into())
        .decrypt_padded_vec_mut::<Pkcs7>(data)
        .ok()
}

fn u64_le(b: &[u8]) -> u64 {
    let mut a = [0u8; 8];
    a.copy_from_slice(&b[..8]);
    u64::from_le_bytes(a)
}

/// Derive the AES session key from the device-provided `seed` (2 bytes) and
/// `srand` (≥16 bytes), mixing in [`LOGIN_KEY`]. Port of `genSessionKey`.
pub fn gen_session_key(seed: &[u8], srand: &[u8]) -> Option<[u8; 16]> {
    if seed.len() < 2 || srand.len() < 16 {
        return None;
    }
    let pos = seed[0] as usize * 0x10 + (seed[1].wrapping_sub(1) as usize) * 0x100;
    if pos + 16 > LOGIN_KEY.len() {
        return None;
    }
    let d0 = u64_le(&LOGIN_KEY[pos..pos + 8]);
    let d1 = u64_le(&LOGIN_KEY[pos + 8..pos + 16]);
    let d2 = u64_le(&srand[0..8]);
    let d3 = u64_le(&srand[8..16]);

    let mut data = Vec::with_capacity(32);
    data.extend_from_slice(&d0.to_le_bytes());
    data.extend_from_slice(&d1.to_le_bytes());
    data.extend_from_slice(&d2.to_le_bytes());
    data.extend_from_slice(&d3.to_le_bytes());
    Some(md5(&data))
}

/// The auth secret sent after the session is established: uppercase-hex MD5 of
/// `user_id + serial`.
pub fn auth_secret(user_id: &str, serial: &str) -> Vec<u8> {
    let digest = md5(format!("{user_id}{serial}").as_bytes());
    let hex: String = digest.iter().map(|b| format!("{b:02X}")).collect();
    hex.into_bytes()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn login_key_embedded() {
        assert!(LOGIN_KEY.len() >= 4096);
    }

    #[test]
    fn aes_roundtrip() {
        let key = [7u8; 16];
        let iv = [9u8; 16];
        let msg = b"hello ecoflow, this is longer than one block";
        let ct = aes_cbc_encrypt(&key, &iv, msg);
        let pt = aes_cbc_decrypt(&key, &iv, &ct).unwrap();
        assert_eq!(pt, msg);
    }

    #[test]
    fn session_key_is_deterministic() {
        let seed = [0x0c, 0x01];
        let srand = [0x11u8; 16];
        let k1 = gen_session_key(&seed, &srand).unwrap();
        let k2 = gen_session_key(&seed, &srand).unwrap();
        assert_eq!(k1, k2);
        assert_eq!(k1.len(), 16);
    }

    #[test]
    fn auth_secret_is_uppercase_hex() {
        let s = auth_secret("123", "HD31ABC");
        assert_eq!(s.len(), 32);
        assert!(s.iter().all(|&c| c.is_ascii_hexdigit() && !c.is_ascii_lowercase()));
    }
}
