//! ZX BLE opcode tables recovered from the device application.
//!
//! Two parallel enums exist: [`ZXOpcodeType`] is the semantic/logical layer used
//! throughout the confer + controller logic, and [`ZXCommonCodeType`] is the
//! transport layer with its own numbering. Per-device opcode maps remap these
//! onto the concrete 2-byte wire pair `[flag, cmd]` (flag `0x00` = our-initiated,
//! `0x08` = alt; the secure `40xx` scheme echoes `0x40`/`0x48`).
//!
//! The [`wire`] submodule holds the authoritative `ZXOpcodeType -> wire opcode`
//! mapping from `PPSDeviceCommands.commonOpcodeMap` (the on-wire low byte with
//! high nibble `0x40`).

/// Semantic/logical ZX opcode layer (from the app object pool).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
#[allow(non_camel_case_types)]
pub enum ZXOpcodeType {
    StartConnectReq = 0x00,
    StartConnectRes = 0x01,
    StartDisconnectReq = 0x02,
    StartDisconnectRes = 0x03,
    CapabilityNegotiationReq = 0x04,
    CapabilityNegotiationRes = 0x05,
    ConfigureCapabilityReq = 0x06,
    SetCapabilityReq = 0x07,
    SetCapabilityRes = 0x08,
    GetDeviceInfoReq = 0x09,
    GetDeviceInfoRes = 0x0a,
    GetAesKeyReq = 0x0b,
    GetAesKeyRes = 0x0c,
    GetAuthenticationReq = 0x0d,
    GetAuthenticationRes = 0x0e,
    BindUserIdReq = 0x0f,
    BindUserIdRes = 0x10,
    GetPublicKeyReq = 0x11,
    GetPublicKeyRes = 0x12,
    ScanWifiReq = 0x13,
    ScanWifiRes = 0x14,
    GetWifiListReq = 0x15,
    GetWifiListRes = 0x16,
    ConnectWifiRes = 0x17,
    ConnectWifiReq = 0x18,
    ActivateWifiReq = 0x19,
    ActivateWifiRes = 0x1a,
    ExitConnectReq = 0x1b,
    ExitConnectRes = 0x1c,
    PostErrorInfoReq = 0x1d,
    PostWorkInfoReq = 0x1e,
    PostSwitchStateReq = 0x1f,
    PostDeviceInfoReq = 0x20,
    PostCountDownTimeReq = 0x21,
    PostLinkageSystemErrorReq = 0x22,
    PostPbFormatBackupMindData = 0x23,
    GetAllDeviceInfoRes = 0x25,
    GetAcCarCountDownTimeRes = 0x27,
    SetAcCountDownTimeRes = 0x29,
    SetCarCountDownTimeRes = 0x2b,
    SetAcChargePowerRes = 0x2d,
    SetDeviceWaitTimeRes = 0x2f,
    SetDeviceScreenTimeRes = 0x31,
    SetInversionWaitTimeRes = 0x33,
    GetZXOTAStateReq = 0x38,
    GetZXOTAStateRes = 0x39,
    SendOtaSubPackageReq = 0x3a,
    GetMicroInverterReq = 0x3b,
    SetDischargeTimeRes = 0x3c,
    SetMajorPkgRes = 0x3e,
    SetMinorPkgRes = 0x40,
    SetAcSwitchRes = 0x42,
    SetCarSwitchRes = 0x44,
    SetLcdLightRes = 0x46,
    SetAcFrequencyRes = 0x48,
    SetEnergyModeRes = 0x4a,
    SetAmbientLightRes = 0x4c,
    SetTempUnitRes = 0x4e,
    SetResetRes = 0x50,
    SetDeviceUpdateEnergyReq = 0x51,
    PostDeviceAllInfoReq = 0x52,
    GetAllBMSSubBatteryInfoReq = 0x53,
    GetAllBMSSubBatteryInfoRes = 0x54,
    PostAllBMSMinorBatteryBTInfoReq = 0x55,
    PostAllBMSMinorBatteryWiFiInfoReq = 0x56,
    PostA17B2DeviceInfoWIFIReq = 0x57,
    PostA17B2DeviceInfoBTReq = 0x58,
    GetA17B2DeviceInfoReq = 0x59,
    GetA17B2DeviceInfoRes = 0x5a,
    SetBMSSubBatteryPowerSwitchReq = 0x5b,
    SetBMSSubBatteryPowerSwitchRes = 0x5c,
    GetDeviceSelfTestRes = 0x5d,
    SetBMSSubBatteryLightSwitchReq = 0x5e,
    SetBMSSubBatteryLightSwitchRes = 0x5f,
    PostSubBatteryErrorInfoReq = 0x60,
    Unknown = 0x61,
    SetSuperChargeReq = 0x62,
    SetSuperChargeRes = 0x63,
    PostUpgradeStateRes = 0x64,
    PostUpgradeStateReq = 0x65,
    DeviceFactorySettingRes = 0x67,
    DeviceFactorySettingReq = 0x68,
    DeviceFactorySettingClearRes = 0x69,
    DeviceFactorySettingClearReq = 0x6a,
    SetA17b1CommandReq = 0x6b,
    SetA17b1CommandRes = 0x6c,
    PostA17b1DeviceInfoReq = 0x6d,
    PostA17b1SelfCheckReq = 0x6e,
    PostDeviceListReq = 0x6f,
    PostGetUpdateListReq = 0x70,
    PostA1790DeviceInfoReq = 0x71,
    SetA1790CommandReq = 0x72,
    GetScanBluetoothDeviceReq = 0x73,
    GetScanBluetoothDeviceRes = 0x74,
    GetBindBluetoothDeviceReq = 0x75,
    GetBindBluetoothDeviceRes = 0x76,
    GetUnBindBluetoothDeviceReq = 0x77,
    GetUnBindBluetoothDeviceRes = 0x78,
    GetModuleInfoReq = 0x79,
    GetModuleInfoRes = 0x7a,
    GetMiniChargeAllDeviceInfoReq = 0x7b,
    GetMiniChargeAllDeviceInfoRes = 0x7c,
    SetMiniChargeResetReq = 0x7d,
    SetMiniChargeResetRes = 0x7e,
    GetMiniChargeScreensaverReq = 0x7f,
    GetMiniChargeScreensaverRes = 0x80,
    SetMiniChargeScreenTimeoutReq = 0x81,
    SetMiniChargeScreenTimeoutRes = 0x82,
    SetMiniChargeScreenBrightnessReq = 0x83,
    SetMiniChargeScreenBrightnessRes = 0x84,
    SetMiniChargeScreensaverReq = 0x85,
    SetMiniChargeScreensaverRes = 0x86,
    SetMiniChargeACRelaySwitchReq = 0x87,
    SetMiniChargeACRelaySwitchRes = 0x88,
    RequestModuleLogUploadReq = 0x89,
    RequestModuleLogUploadRes = 0x8a,
    ModuleLogUploadRes = 0x8b,
    RequestMcuLogUploadReq = 0x8c,
    RequestMcuLogUploadRes = 0x8d,
    McuLogUploadReq = 0x8e,
    McuLogUploadRes = 0x8f,
    BleOtaProgressReq = 0x90,
    BleOtaProgressRes = 0x91,
    CarPortSavingReq = 0x92,
    CarPortSavingRes = 0x93,
    AcOutputSmartReq = 0x94,
    AcOutputSmartRes = 0x95,
    SetRelaySwitchReq = 0x96,
    SetRelaySwitchRes = 0x97,
    SetTimingReq = 0x98,
    SetTimingRes = 0x99,
    GetTimingReq = 0x9a,
    GetTimingRes = 0x9b,
    SetCountdownReq = 0x9c,
    SetCountdownRes = 0x9d,
    GetCountdownReq = 0x9e,
    GetCountdownRes = 0x9f,
    SetLocationLightReq = 0xa0,
    SetLocationLightRes = 0xa1,
    SetMultiDevicesReq = 0xa2,
    SetMultiDevicesRes = 0xa3,
    GetMultiDevicesReq = 0xa4,
    GetMultiDevicesRes = 0xa5,
    GetOTAStateReq = 0xa6,
    GetOTAStateRes = 0xa7,
    UpUpgradeCondition = 0xa8,
}

impl ZXOpcodeType {
    /// The recovered symbol name from the app.
    pub fn name(self) -> &'static str {
        match self {
            Self::StartConnectReq => "startConnectReq",
            Self::StartConnectRes => "startConnectRes",
            Self::StartDisconnectReq => "startDisconnectReq",
            Self::StartDisconnectRes => "startDisconnectRes",
            Self::CapabilityNegotiationReq => "capabilityNegotiationReq",
            Self::CapabilityNegotiationRes => "capabilityNegotiationRes",
            Self::ConfigureCapabilityReq => "configureCapabilityReq",
            Self::SetCapabilityReq => "setCapabilityReq",
            Self::SetCapabilityRes => "setCapabilityRes",
            Self::GetDeviceInfoReq => "getDeviceInfoReq",
            Self::GetDeviceInfoRes => "getDeviceInfoRes",
            Self::GetAesKeyReq => "getAesKeyReq",
            Self::GetAesKeyRes => "getAesKeyRes",
            Self::GetAuthenticationReq => "getAuthenticationReq",
            Self::GetAuthenticationRes => "getAuthenticationRes",
            Self::BindUserIdReq => "bindUserIdReq",
            Self::BindUserIdRes => "bindUserIdRes",
            Self::GetPublicKeyReq => "getPublicKeyReq",
            Self::GetPublicKeyRes => "getPublicKeyRes",
            Self::ScanWifiReq => "scanWifiReq",
            Self::ScanWifiRes => "scanWifiRes",
            Self::GetWifiListReq => "getWifiListReq",
            Self::GetWifiListRes => "getWifiListRes",
            Self::ConnectWifiRes => "connectWifiRes",
            Self::ConnectWifiReq => "connectWifiReq",
            Self::ActivateWifiReq => "activateWifiReq",
            Self::ActivateWifiRes => "activateWifiRes",
            Self::ExitConnectReq => "exitConnectReq",
            Self::ExitConnectRes => "exitConnectRes",
            Self::PostErrorInfoReq => "postErrorInfoReq",
            Self::PostWorkInfoReq => "postWorkInfoReq",
            Self::PostSwitchStateReq => "postSwitchStateReq",
            Self::PostDeviceInfoReq => "postDeviceInfoReq",
            Self::PostCountDownTimeReq => "postCountDownTimeReq",
            Self::PostLinkageSystemErrorReq => "postLinkageSystemErrorReq",
            Self::PostPbFormatBackupMindData => "postPbFormatBackupMindData",
            Self::GetAllDeviceInfoRes => "getAllDeviceInfoRes",
            Self::GetAcCarCountDownTimeRes => "getAcCarCountDownTimeRes",
            Self::SetAcCountDownTimeRes => "setAcCountDownTimeRes",
            Self::SetCarCountDownTimeRes => "setCarCountDownTimeRes",
            Self::SetAcChargePowerRes => "setAcChargePowerRes",
            Self::SetDeviceWaitTimeRes => "setDeviceWaitTimeRes",
            Self::SetDeviceScreenTimeRes => "setDeviceScreenTimeRes",
            Self::SetInversionWaitTimeRes => "setInversionWaitTimeRes",
            Self::GetZXOTAStateReq => "getZXOTAStateReq",
            Self::GetZXOTAStateRes => "getZXOTAStateRes",
            Self::SendOtaSubPackageReq => "sendOtaSubPackageReq",
            Self::GetMicroInverterReq => "getMicroInverterReq",
            Self::SetDischargeTimeRes => "setDischargeTimeRes",
            Self::SetMajorPkgRes => "setMajorPkgRes",
            Self::SetMinorPkgRes => "setMinorPkgRes",
            Self::SetAcSwitchRes => "setAcSwitchRes",
            Self::SetCarSwitchRes => "setCarSwitchRes",
            Self::SetLcdLightRes => "setLcdLightRes",
            Self::SetAcFrequencyRes => "setAcFrequencyRes",
            Self::SetEnergyModeRes => "setEnergyModeRes",
            Self::SetAmbientLightRes => "setAmbientLightRes",
            Self::SetTempUnitRes => "setTempUnitRes",
            Self::SetResetRes => "setResetRes",
            Self::SetDeviceUpdateEnergyReq => "setDeviceUpdateEnergyReq",
            Self::PostDeviceAllInfoReq => "postDeviceAllInfoReq",
            Self::GetAllBMSSubBatteryInfoReq => "getAllBMSSubBatteryInfoReq",
            Self::GetAllBMSSubBatteryInfoRes => "getAllBMSSubBatteryInfoRes",
            Self::PostAllBMSMinorBatteryBTInfoReq => "postAllBMSMinorBatteryBTInfoReq",
            Self::PostAllBMSMinorBatteryWiFiInfoReq => "postAllBMSMinorBatteryWiFiInfoReq",
            Self::PostA17B2DeviceInfoWIFIReq => "postA17B2DeviceInfoWIFIReq",
            Self::PostA17B2DeviceInfoBTReq => "postA17B2DeviceInfoBTReq",
            Self::GetA17B2DeviceInfoReq => "getA17B2DeviceInfoReq",
            Self::GetA17B2DeviceInfoRes => "getA17B2DeviceInfoRes",
            Self::SetBMSSubBatteryPowerSwitchReq => "setBMSSubBatteryPowerSwitchReq",
            Self::SetBMSSubBatteryPowerSwitchRes => "setBMSSubBatteryPowerSwitchRes",
            Self::GetDeviceSelfTestRes => "getDeviceSelfTestRes",
            Self::SetBMSSubBatteryLightSwitchReq => "setBMSSubBatteryLightSwitchReq",
            Self::SetBMSSubBatteryLightSwitchRes => "setBMSSubBatteryLightSwitchRes",
            Self::PostSubBatteryErrorInfoReq => "postSubBatteryErrorInfoReq",
            Self::Unknown => "unknown",
            Self::SetSuperChargeReq => "setSuperChargeReq",
            Self::SetSuperChargeRes => "setSuperChargeRes",
            Self::PostUpgradeStateRes => "postUpgradeStateRes",
            Self::PostUpgradeStateReq => "postUpgradeStateReq",
            Self::DeviceFactorySettingRes => "deviceFactorySettingRes",
            Self::DeviceFactorySettingReq => "deviceFactorySettingReq",
            Self::DeviceFactorySettingClearRes => "deviceFactorySettingClearRes",
            Self::DeviceFactorySettingClearReq => "deviceFactorySettingClearReq",
            Self::SetA17b1CommandReq => "setA17b1CommandReq",
            Self::SetA17b1CommandRes => "setA17b1CommandRes",
            Self::PostA17b1DeviceInfoReq => "postA17b1DeviceInfoReq",
            Self::PostA17b1SelfCheckReq => "postA17b1SelfCheckReq",
            Self::PostDeviceListReq => "postDeviceListReq",
            Self::PostGetUpdateListReq => "postGetUpdateListReq",
            Self::PostA1790DeviceInfoReq => "postA1790DeviceInfoReq",
            Self::SetA1790CommandReq => "setA1790CommandReq",
            Self::GetScanBluetoothDeviceReq => "getScanBluetoothDeviceReq",
            Self::GetScanBluetoothDeviceRes => "getScanBluetoothDeviceRes",
            Self::GetBindBluetoothDeviceReq => "getBindBluetoothDeviceReq",
            Self::GetBindBluetoothDeviceRes => "getBindBluetoothDeviceRes",
            Self::GetUnBindBluetoothDeviceReq => "getUnBindBluetoothDeviceReq",
            Self::GetUnBindBluetoothDeviceRes => "getUnBindBluetoothDeviceRes",
            Self::GetModuleInfoReq => "getModuleInfoReq",
            Self::GetModuleInfoRes => "getModuleInfoRes",
            Self::GetMiniChargeAllDeviceInfoReq => "getMiniChargeAllDeviceInfoReq",
            Self::GetMiniChargeAllDeviceInfoRes => "getMiniChargeAllDeviceInfoRes",
            Self::SetMiniChargeResetReq => "setMiniChargeResetReq",
            Self::SetMiniChargeResetRes => "setMiniChargeResetRes",
            Self::GetMiniChargeScreensaverReq => "getMiniChargeScreensaverReq",
            Self::GetMiniChargeScreensaverRes => "getMiniChargeScreensaverRes",
            Self::SetMiniChargeScreenTimeoutReq => "setMiniChargeScreenTimeoutReq",
            Self::SetMiniChargeScreenTimeoutRes => "setMiniChargeScreenTimeoutRes",
            Self::SetMiniChargeScreenBrightnessReq => "setMiniChargeScreenBrightnessReq",
            Self::SetMiniChargeScreenBrightnessRes => "setMiniChargeScreenBrightnessRes",
            Self::SetMiniChargeScreensaverReq => "setMiniChargeScreensaverReq",
            Self::SetMiniChargeScreensaverRes => "setMiniChargeScreensaverRes",
            Self::SetMiniChargeACRelaySwitchReq => "setMiniChargeACRelaySwitchReq",
            Self::SetMiniChargeACRelaySwitchRes => "setMiniChargeACRelaySwitchRes",
            Self::RequestModuleLogUploadReq => "requestModuleLogUploadReq",
            Self::RequestModuleLogUploadRes => "requestModuleLogUploadRes",
            Self::ModuleLogUploadRes => "moduleLogUploadRes",
            Self::RequestMcuLogUploadReq => "requestMcuLogUploadReq",
            Self::RequestMcuLogUploadRes => "requestMcuLogUploadRes",
            Self::McuLogUploadReq => "mcuLogUploadReq",
            Self::McuLogUploadRes => "mcuLogUploadRes",
            Self::BleOtaProgressReq => "bleOtaProgressReq",
            Self::BleOtaProgressRes => "bleOtaProgressRes",
            Self::CarPortSavingReq => "carPortSavingReq",
            Self::CarPortSavingRes => "carPortSavingRes",
            Self::AcOutputSmartReq => "acOutputSmartReq",
            Self::AcOutputSmartRes => "acOutputSmartRes",
            Self::SetRelaySwitchReq => "setRelaySwitchReq",
            Self::SetRelaySwitchRes => "setRelaySwitchRes",
            Self::SetTimingReq => "setTimingReq",
            Self::SetTimingRes => "setTimingRes",
            Self::GetTimingReq => "getTimingReq",
            Self::GetTimingRes => "getTimingRes",
            Self::SetCountdownReq => "setCountdownReq",
            Self::SetCountdownRes => "setCountdownRes",
            Self::GetCountdownReq => "getCountdownReq",
            Self::GetCountdownRes => "getCountdownRes",
            Self::SetLocationLightReq => "setLocationLightReq",
            Self::SetLocationLightRes => "setLocationLightRes",
            Self::SetMultiDevicesReq => "setMultiDevicesReq",
            Self::SetMultiDevicesRes => "setMultiDevicesRes",
            Self::GetMultiDevicesReq => "getMultiDevicesReq",
            Self::GetMultiDevicesRes => "getMultiDevicesRes",
            Self::GetOTAStateReq => "getOTAStateReq",
            Self::GetOTAStateRes => "getOTAStateRes",
            Self::UpUpgradeCondition => "upUpgradeCondition",
        }
    }
    /// Look up by numeric opcode.
    pub fn from_code(code: u16) -> Option<Self> {
        Some(match code {
            0x00 => Self::StartConnectReq,
            0x01 => Self::StartConnectRes,
            0x02 => Self::StartDisconnectReq,
            0x03 => Self::StartDisconnectRes,
            0x04 => Self::CapabilityNegotiationReq,
            0x05 => Self::CapabilityNegotiationRes,
            0x06 => Self::ConfigureCapabilityReq,
            0x07 => Self::SetCapabilityReq,
            0x08 => Self::SetCapabilityRes,
            0x09 => Self::GetDeviceInfoReq,
            0x0a => Self::GetDeviceInfoRes,
            0x0b => Self::GetAesKeyReq,
            0x0c => Self::GetAesKeyRes,
            0x0d => Self::GetAuthenticationReq,
            0x0e => Self::GetAuthenticationRes,
            0x0f => Self::BindUserIdReq,
            0x10 => Self::BindUserIdRes,
            0x11 => Self::GetPublicKeyReq,
            0x12 => Self::GetPublicKeyRes,
            0x13 => Self::ScanWifiReq,
            0x14 => Self::ScanWifiRes,
            0x15 => Self::GetWifiListReq,
            0x16 => Self::GetWifiListRes,
            0x17 => Self::ConnectWifiRes,
            0x18 => Self::ConnectWifiReq,
            0x19 => Self::ActivateWifiReq,
            0x1a => Self::ActivateWifiRes,
            0x1b => Self::ExitConnectReq,
            0x1c => Self::ExitConnectRes,
            0x1d => Self::PostErrorInfoReq,
            0x1e => Self::PostWorkInfoReq,
            0x1f => Self::PostSwitchStateReq,
            0x20 => Self::PostDeviceInfoReq,
            0x21 => Self::PostCountDownTimeReq,
            0x22 => Self::PostLinkageSystemErrorReq,
            0x23 => Self::PostPbFormatBackupMindData,
            0x25 => Self::GetAllDeviceInfoRes,
            0x27 => Self::GetAcCarCountDownTimeRes,
            0x29 => Self::SetAcCountDownTimeRes,
            0x2b => Self::SetCarCountDownTimeRes,
            0x2d => Self::SetAcChargePowerRes,
            0x2f => Self::SetDeviceWaitTimeRes,
            0x31 => Self::SetDeviceScreenTimeRes,
            0x33 => Self::SetInversionWaitTimeRes,
            0x38 => Self::GetZXOTAStateReq,
            0x39 => Self::GetZXOTAStateRes,
            0x3a => Self::SendOtaSubPackageReq,
            0x3b => Self::GetMicroInverterReq,
            0x3c => Self::SetDischargeTimeRes,
            0x3e => Self::SetMajorPkgRes,
            0x40 => Self::SetMinorPkgRes,
            0x42 => Self::SetAcSwitchRes,
            0x44 => Self::SetCarSwitchRes,
            0x46 => Self::SetLcdLightRes,
            0x48 => Self::SetAcFrequencyRes,
            0x4a => Self::SetEnergyModeRes,
            0x4c => Self::SetAmbientLightRes,
            0x4e => Self::SetTempUnitRes,
            0x50 => Self::SetResetRes,
            0x51 => Self::SetDeviceUpdateEnergyReq,
            0x52 => Self::PostDeviceAllInfoReq,
            0x53 => Self::GetAllBMSSubBatteryInfoReq,
            0x54 => Self::GetAllBMSSubBatteryInfoRes,
            0x55 => Self::PostAllBMSMinorBatteryBTInfoReq,
            0x56 => Self::PostAllBMSMinorBatteryWiFiInfoReq,
            0x57 => Self::PostA17B2DeviceInfoWIFIReq,
            0x58 => Self::PostA17B2DeviceInfoBTReq,
            0x59 => Self::GetA17B2DeviceInfoReq,
            0x5a => Self::GetA17B2DeviceInfoRes,
            0x5b => Self::SetBMSSubBatteryPowerSwitchReq,
            0x5c => Self::SetBMSSubBatteryPowerSwitchRes,
            0x5d => Self::GetDeviceSelfTestRes,
            0x5e => Self::SetBMSSubBatteryLightSwitchReq,
            0x5f => Self::SetBMSSubBatteryLightSwitchRes,
            0x60 => Self::PostSubBatteryErrorInfoReq,
            0x61 => Self::Unknown,
            0x62 => Self::SetSuperChargeReq,
            0x63 => Self::SetSuperChargeRes,
            0x64 => Self::PostUpgradeStateRes,
            0x65 => Self::PostUpgradeStateReq,
            0x67 => Self::DeviceFactorySettingRes,
            0x68 => Self::DeviceFactorySettingReq,
            0x69 => Self::DeviceFactorySettingClearRes,
            0x6a => Self::DeviceFactorySettingClearReq,
            0x6b => Self::SetA17b1CommandReq,
            0x6c => Self::SetA17b1CommandRes,
            0x6d => Self::PostA17b1DeviceInfoReq,
            0x6e => Self::PostA17b1SelfCheckReq,
            0x6f => Self::PostDeviceListReq,
            0x70 => Self::PostGetUpdateListReq,
            0x71 => Self::PostA1790DeviceInfoReq,
            0x72 => Self::SetA1790CommandReq,
            0x73 => Self::GetScanBluetoothDeviceReq,
            0x74 => Self::GetScanBluetoothDeviceRes,
            0x75 => Self::GetBindBluetoothDeviceReq,
            0x76 => Self::GetBindBluetoothDeviceRes,
            0x77 => Self::GetUnBindBluetoothDeviceReq,
            0x78 => Self::GetUnBindBluetoothDeviceRes,
            0x79 => Self::GetModuleInfoReq,
            0x7a => Self::GetModuleInfoRes,
            0x7b => Self::GetMiniChargeAllDeviceInfoReq,
            0x7c => Self::GetMiniChargeAllDeviceInfoRes,
            0x7d => Self::SetMiniChargeResetReq,
            0x7e => Self::SetMiniChargeResetRes,
            0x7f => Self::GetMiniChargeScreensaverReq,
            0x80 => Self::GetMiniChargeScreensaverRes,
            0x81 => Self::SetMiniChargeScreenTimeoutReq,
            0x82 => Self::SetMiniChargeScreenTimeoutRes,
            0x83 => Self::SetMiniChargeScreenBrightnessReq,
            0x84 => Self::SetMiniChargeScreenBrightnessRes,
            0x85 => Self::SetMiniChargeScreensaverReq,
            0x86 => Self::SetMiniChargeScreensaverRes,
            0x87 => Self::SetMiniChargeACRelaySwitchReq,
            0x88 => Self::SetMiniChargeACRelaySwitchRes,
            0x89 => Self::RequestModuleLogUploadReq,
            0x8a => Self::RequestModuleLogUploadRes,
            0x8b => Self::ModuleLogUploadRes,
            0x8c => Self::RequestMcuLogUploadReq,
            0x8d => Self::RequestMcuLogUploadRes,
            0x8e => Self::McuLogUploadReq,
            0x8f => Self::McuLogUploadRes,
            0x90 => Self::BleOtaProgressReq,
            0x91 => Self::BleOtaProgressRes,
            0x92 => Self::CarPortSavingReq,
            0x93 => Self::CarPortSavingRes,
            0x94 => Self::AcOutputSmartReq,
            0x95 => Self::AcOutputSmartRes,
            0x96 => Self::SetRelaySwitchReq,
            0x97 => Self::SetRelaySwitchRes,
            0x98 => Self::SetTimingReq,
            0x99 => Self::SetTimingRes,
            0x9a => Self::GetTimingReq,
            0x9b => Self::GetTimingRes,
            0x9c => Self::SetCountdownReq,
            0x9d => Self::SetCountdownRes,
            0x9e => Self::GetCountdownReq,
            0x9f => Self::GetCountdownRes,
            0xa0 => Self::SetLocationLightReq,
            0xa1 => Self::SetLocationLightRes,
            0xa2 => Self::SetMultiDevicesReq,
            0xa3 => Self::SetMultiDevicesRes,
            0xa4 => Self::GetMultiDevicesReq,
            0xa5 => Self::GetMultiDevicesRes,
            0xa6 => Self::GetOTAStateReq,
            0xa7 => Self::GetOTAStateRes,
            0xa8 => Self::UpUpgradeCondition,
            _ => return None,
        })
    }
}

/// Transport-layer ZX opcode numbering (from the app object pool).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
#[allow(non_camel_case_types)]
pub enum ZXCommonCodeType {
    StartConnectReq = 0x00,
    StartConnectRes = 0x01,
    StartDisconnectReq = 0x02,
    StartDisconnectRes = 0x03,
    CapabilityNegotiationReq = 0x04,
    CapabilityNegotiationRes = 0x05,
    ConfigureCapabilityReq = 0x06,
    SetCapabilityReq = 0x07,
    SetCapabilityRes = 0x08,
    GetDeviceInfoReq = 0x09,
    GetDeviceInfoRes = 0x0a,
    GetAesKeyReq = 0x0b,
    GetAesKeyRes = 0x0c,
    BindUserIdReq = 0x0d,
    BindUserIdRes = 0x0e,
    GetAuthenticationReq = 0x10,
    GetAuthenticationRes = 0x11,
    ScanWifiReq = 0x12,
    ScanWifiRes = 0x13,
    GetWifiListReq = 0x14,
    GetWifiListRes = 0x15,
    ConnectWifiRes = 0x16,
    ConnectWifiReq = 0x17,
    DeployWifiReq = 0x18,
    DeployWifiRes = 0x19,
    VerifyPassReq = 0x1a,
    VerifyPassRes = 0x1b,
    StartOtaReq = 0x1c,
    StartOtaRes = 0x1d,
    RouteOkReq = 0x1e,
    RouteOkRes = 0x1f,
    ServerOkReq = 0x20,
    ServerOkRes = 0x21,
    NetOkReq = 0x22,
    NetOkRes = 0x23,
    GetWifiInfoReq = 0x24,
    GetWifiInfoRes = 0x25,
    OtaLoadingReq = 0x26,
    OtaDownloadReq = 0x27,
    SetAttRes = 0x28,
    SetAttReq = 0x29,
    GetAttReq = 0x2a,
    GetAttRes = 0x2b,
    DeviceErrorReportReq = 0x2c,
    DeviceAttReportReq = 0x2d,
    DeviceCardListReportReq = 0x2e,
    DeviceAttReportRes = 0x2f,
    DeviceListReportReq = 0x30,
    DeviceListReportRes = 0x31,
    OtaResultReq = 0x32,
    OtaResultRes = 0x33,
    BlePeakValleyReq = 0x34,
    BlePeakValleyRes = 0x35,
    SocResultReq = 0x36,
    SocResultRes = 0x37,
    DeviceCardListReq = 0x38,
    DeviceCardListRes = 0x39,
    OtaProgressReq = 0x3a,
    EventReport = 0x3b,
    BackupHistoryReq = 0x3c,
    BackupHistoryRes = 0x3d,
    AutoDisasterReq = 0x3e,
    AutoDisasterRes = 0x3f,
    ItalySelfCheckReq = 0x40,
    HeatPumpTimeReq = 0x41,
    HeatPumpTimeRes = 0x42,
    GetAtsAndMiFaultReq = 0x43,
    GetAtsAndMiFaultRes = 0x44,
    GetBleOtaStatusReq = 0x45,
    GetBleOtaStatusRes = 0x46,
    Get5101ZXOTAStateReq = 0x47,
    Get5101ZXOTAStateRes = 0x48,
    StartBleOtaReq = 0x49,
    StartBleOtaRes = 0x4a,
    SendOtaDataReq = 0x4b,
    SendOtaDataRes = 0x4c,
    NewDeviceListReportRes = 0x4d,
    NewDeviceVersionReportRes = 0x4e,
    ReportState = 0x4f,
    Unknown = 0x50,
}

impl ZXCommonCodeType {
    /// The recovered symbol name from the app.
    pub fn name(self) -> &'static str {
        match self {
            Self::StartConnectReq => "startConnectReq",
            Self::StartConnectRes => "startConnectRes",
            Self::StartDisconnectReq => "startDisconnectReq",
            Self::StartDisconnectRes => "startDisconnectRes",
            Self::CapabilityNegotiationReq => "capabilityNegotiationReq",
            Self::CapabilityNegotiationRes => "capabilityNegotiationRes",
            Self::ConfigureCapabilityReq => "configureCapabilityReq",
            Self::SetCapabilityReq => "setCapabilityReq",
            Self::SetCapabilityRes => "setCapabilityRes",
            Self::GetDeviceInfoReq => "getDeviceInfoReq",
            Self::GetDeviceInfoRes => "getDeviceInfoRes",
            Self::GetAesKeyReq => "getAesKeyReq",
            Self::GetAesKeyRes => "getAesKeyRes",
            Self::BindUserIdReq => "bindUserIdReq",
            Self::BindUserIdRes => "bindUserIdRes",
            Self::GetAuthenticationReq => "getAuthenticationReq",
            Self::GetAuthenticationRes => "getAuthenticationRes",
            Self::ScanWifiReq => "scanWifiReq",
            Self::ScanWifiRes => "scanWifiRes",
            Self::GetWifiListReq => "getWifiListReq",
            Self::GetWifiListRes => "getWifiListRes",
            Self::ConnectWifiRes => "connectWifiRes",
            Self::ConnectWifiReq => "connectWifiReq",
            Self::DeployWifiReq => "deployWifiReq",
            Self::DeployWifiRes => "deployWifiRes",
            Self::VerifyPassReq => "verifyPassReq",
            Self::VerifyPassRes => "verifyPassRes",
            Self::StartOtaReq => "startOtaReq",
            Self::StartOtaRes => "startOtaRes",
            Self::RouteOkReq => "routeOkReq",
            Self::RouteOkRes => "routeOkRes",
            Self::ServerOkReq => "serverOkReq",
            Self::ServerOkRes => "serverOkRes",
            Self::NetOkReq => "netOkReq",
            Self::NetOkRes => "netOkRes",
            Self::GetWifiInfoReq => "getWifiInfoReq",
            Self::GetWifiInfoRes => "getWifiInfoRes",
            Self::OtaLoadingReq => "otaLoadingReq",
            Self::OtaDownloadReq => "otaDownloadReq",
            Self::SetAttRes => "setAttRes",
            Self::SetAttReq => "setAttReq",
            Self::GetAttReq => "getAttReq",
            Self::GetAttRes => "getAttRes",
            Self::DeviceErrorReportReq => "deviceErrorReportReq",
            Self::DeviceAttReportReq => "deviceAttReportReq",
            Self::DeviceCardListReportReq => "deviceCardListReportReq",
            Self::DeviceAttReportRes => "deviceAttReportRes",
            Self::DeviceListReportReq => "deviceListReportReq",
            Self::DeviceListReportRes => "deviceListReportRes",
            Self::OtaResultReq => "otaResultReq",
            Self::OtaResultRes => "otaResultRes",
            Self::BlePeakValleyReq => "blePeakValleyReq",
            Self::BlePeakValleyRes => "blePeakValleyRes",
            Self::SocResultReq => "socResultReq",
            Self::SocResultRes => "socResultRes",
            Self::DeviceCardListReq => "deviceCardListReq",
            Self::DeviceCardListRes => "deviceCardListRes",
            Self::OtaProgressReq => "otaProgressReq",
            Self::EventReport => "eventReport",
            Self::BackupHistoryReq => "backupHistoryReq",
            Self::BackupHistoryRes => "backupHistoryRes",
            Self::AutoDisasterReq => "autoDisasterReq",
            Self::AutoDisasterRes => "autoDisasterRes",
            Self::ItalySelfCheckReq => "italySelfCheckReq",
            Self::HeatPumpTimeReq => "heatPumpTimeReq",
            Self::HeatPumpTimeRes => "heatPumpTimeRes",
            Self::GetAtsAndMiFaultReq => "getAtsAndMiFaultReq",
            Self::GetAtsAndMiFaultRes => "getAtsAndMiFaultRes",
            Self::GetBleOtaStatusReq => "getBleOtaStatusReq",
            Self::GetBleOtaStatusRes => "getBleOtaStatusRes",
            Self::Get5101ZXOTAStateReq => "get5101ZXOTAStateReq",
            Self::Get5101ZXOTAStateRes => "get5101ZXOTAStateRes",
            Self::StartBleOtaReq => "startBleOtaReq",
            Self::StartBleOtaRes => "startBleOtaRes",
            Self::SendOtaDataReq => "sendOtaDataReq",
            Self::SendOtaDataRes => "sendOtaDataRes",
            Self::NewDeviceListReportRes => "newDeviceListReportRes",
            Self::NewDeviceVersionReportRes => "newDeviceVersionReportRes",
            Self::ReportState => "reportState",
            Self::Unknown => "unknown",
        }
    }
    /// Look up by numeric opcode.
    pub fn from_code(code: u16) -> Option<Self> {
        Some(match code {
            0x00 => Self::StartConnectReq,
            0x01 => Self::StartConnectRes,
            0x02 => Self::StartDisconnectReq,
            0x03 => Self::StartDisconnectRes,
            0x04 => Self::CapabilityNegotiationReq,
            0x05 => Self::CapabilityNegotiationRes,
            0x06 => Self::ConfigureCapabilityReq,
            0x07 => Self::SetCapabilityReq,
            0x08 => Self::SetCapabilityRes,
            0x09 => Self::GetDeviceInfoReq,
            0x0a => Self::GetDeviceInfoRes,
            0x0b => Self::GetAesKeyReq,
            0x0c => Self::GetAesKeyRes,
            0x0d => Self::BindUserIdReq,
            0x0e => Self::BindUserIdRes,
            0x10 => Self::GetAuthenticationReq,
            0x11 => Self::GetAuthenticationRes,
            0x12 => Self::ScanWifiReq,
            0x13 => Self::ScanWifiRes,
            0x14 => Self::GetWifiListReq,
            0x15 => Self::GetWifiListRes,
            0x16 => Self::ConnectWifiRes,
            0x17 => Self::ConnectWifiReq,
            0x18 => Self::DeployWifiReq,
            0x19 => Self::DeployWifiRes,
            0x1a => Self::VerifyPassReq,
            0x1b => Self::VerifyPassRes,
            0x1c => Self::StartOtaReq,
            0x1d => Self::StartOtaRes,
            0x1e => Self::RouteOkReq,
            0x1f => Self::RouteOkRes,
            0x20 => Self::ServerOkReq,
            0x21 => Self::ServerOkRes,
            0x22 => Self::NetOkReq,
            0x23 => Self::NetOkRes,
            0x24 => Self::GetWifiInfoReq,
            0x25 => Self::GetWifiInfoRes,
            0x26 => Self::OtaLoadingReq,
            0x27 => Self::OtaDownloadReq,
            0x28 => Self::SetAttRes,
            0x29 => Self::SetAttReq,
            0x2a => Self::GetAttReq,
            0x2b => Self::GetAttRes,
            0x2c => Self::DeviceErrorReportReq,
            0x2d => Self::DeviceAttReportReq,
            0x2e => Self::DeviceCardListReportReq,
            0x2f => Self::DeviceAttReportRes,
            0x30 => Self::DeviceListReportReq,
            0x31 => Self::DeviceListReportRes,
            0x32 => Self::OtaResultReq,
            0x33 => Self::OtaResultRes,
            0x34 => Self::BlePeakValleyReq,
            0x35 => Self::BlePeakValleyRes,
            0x36 => Self::SocResultReq,
            0x37 => Self::SocResultRes,
            0x38 => Self::DeviceCardListReq,
            0x39 => Self::DeviceCardListRes,
            0x3a => Self::OtaProgressReq,
            0x3b => Self::EventReport,
            0x3c => Self::BackupHistoryReq,
            0x3d => Self::BackupHistoryRes,
            0x3e => Self::AutoDisasterReq,
            0x3f => Self::AutoDisasterRes,
            0x40 => Self::ItalySelfCheckReq,
            0x41 => Self::HeatPumpTimeReq,
            0x42 => Self::HeatPumpTimeRes,
            0x43 => Self::GetAtsAndMiFaultReq,
            0x44 => Self::GetAtsAndMiFaultRes,
            0x45 => Self::GetBleOtaStatusReq,
            0x46 => Self::GetBleOtaStatusRes,
            0x47 => Self::Get5101ZXOTAStateReq,
            0x48 => Self::Get5101ZXOTAStateRes,
            0x49 => Self::StartBleOtaReq,
            0x4a => Self::StartBleOtaRes,
            0x4b => Self::SendOtaDataReq,
            0x4c => Self::SendOtaDataRes,
            0x4d => Self::NewDeviceListReportRes,
            0x4e => Self::NewDeviceVersionReportRes,
            0x4f => Self::ReportState,
            0x50 => Self::Unknown,
            _ => return None,
        })
    }
}

/// Authoritative `ZXOpcodeType` -> on-wire opcode (`0x40xx`) mappings
/// recovered from `PPSDeviceCommands.commonOpcodeMap`.
pub mod wire {
    /// `startConnectReq`
    pub const START_CONNECT_REQ: [u8; 2] = [0x40, 0x01];
    /// `startDisconnectReq`
    pub const START_DISCONNECT_REQ: [u8; 2] = [0x40, 0x02];
    /// `capabilityNegotiationReq`
    pub const CAPABILITY_NEGOTIATION_REQ: [u8; 2] = [0x40, 0x03];
    /// `setCapabilityReq`
    pub const SET_CAPABILITY_REQ: [u8; 2] = [0x40, 0x05];
    /// `getPublicKeyReq`
    pub const GET_PUBLIC_KEY_REQ: [u8; 2] = [0x40, 0x21];
    /// `getAesKeyReq`
    pub const GET_AES_KEY_REQ: [u8; 2] = [0x40, 0x22];
    /// `bindUserIdReq`
    pub const BIND_USER_ID_REQ: [u8; 2] = [0x40, 0x23];
    /// `getAuthenticationReq`
    pub const GET_AUTHENTICATION_REQ: [u8; 2] = [0x40, 0x27];
    /// `getDeviceInfoReq`
    pub const GET_DEVICE_INFO_REQ: [u8; 2] = [0x40, 0x29];
    /// `requestModuleLogUploadReq`
    pub const REQUEST_MODULE_LOG_UPLOAD_REQ: [u8; 2] = [0x40, 0x31];

    // --- Device commands (C1000 Gen 2, empirically verified on hardware) -----
    //
    // Post-handshake control/telemetry commands use high byte `0x41` (the
    // handshake `40xx` frames above are a different function category). These
    // four are confirmed working against a live A1763; the wire/enum mapping for
    // other device settings (e.g. the charge/discharge SoC limit *write*) lives
    // in a device-specific opcode map that is not yet pinned — the SoC limit is
    // currently only *read* (from the pushed `d9` telemetry parameter).

    /// Subscribe to telemetry (payload `a1 01 21`); telemetry then streams on
    /// the `c421` / `c900` parameters.
    pub const SUBSCRIBE: [u8; 2] = [0x41, 0x00];
    /// Toggle the AC output.
    pub const AC_OUTPUT: [u8; 2] = [0x41, 0x01];
    /// Toggle the DC (12 V) output.
    pub const DC_OUTPUT: [u8; 2] = [0x41, 0x02];
    /// Toggle the LCD display.
    pub const DISPLAY: [u8; 2] = [0x41, 0x03];
}
